# Apache
PHPLDAPADMIN_SERVER_ADMIN: webmaster@example.org
PHPLDAPADMIN_SERVER_PATH: /phpldapadmin

# Self signed certificat will be generated
# if PHPLDAPADMIN_HTTPS is set to true and no certificat and key are provided.

# To use your custom certificat and key 2 options :
# - add them in service/phpldapadmin/assets/apache2/certs and build the image
# - or during docker run mount a data volume with those files to /container/service/phpldapadmin/assets/apache2/certs
PHPLDAPADMIN_HTTPS: true
PHPLDAPADMIN_HTTPS_CRT_FILENAME: phpldapadmin.crt
PHPLDAPADMIN_HTTPS_KEY_FILENAME: phpldapadmin.key
PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: ca.crt
PHPLDAPADMIN_HTTPS_VERIFY_CLIENT: optional
PHPLDAPADMIN_HTTPS_VERIFY_DEPTH: "1"

PHPLDAPADMIN_TRUST_PROXY_SSL: false

# ssl-helper environment variables prefix
PHPLDAPADMIN_SSL_HELPER_PREFIX: phpldapadmin # ssl-helper first search config from PHPLDAPADMIN_SSL_HELPER_* variables, before SSL_HELPER_* variables.
